// <auto-generated />
using System;
using InteractiveHub.Service.ClassManagement.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InteractiveHub.Service.ClassRelated.Migrations
{
    [DbContext(typeof(ClassDbContext))]
    [Migration("20251102140259_AddAIConversations")]
    partial class AddAIConversations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InteractiveHub.Service.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(0);

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasBeenActivated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CourseId", "IsActive");

                    b.ToTable("Activities");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.AIConversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeneratedActivityId")
                        .HasColumnType("longtext");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("InstructorId", "CourseId", "IsCompleted");

                    b.ToTable("AIConversations");
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.AIConversationMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PdfContent")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ConversationId", "Order");

                    b.ToTable("AIConversationMessages");
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.AIPdfFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("AIPdfFiles");
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.RealtimeClass", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(0);

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("OwnerId");

                    b.ToTable("RealtimeClass");
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StudentId", "OwnerId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.TeachingCourse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(0);

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.PrimitiveCollection<string>("JoinCheckingModes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("JoinCode")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CourseCode", "AcademicYear", "Semester", "OwnerId")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("InteractiveHub.Service.Submission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(0);

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CourseId", "ActivityId");

                    b.HasIndex("StudentId", "ActivityId");

                    b.ToTable("Submissions");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudentTeachingCourse", b =>
                {
                    b.Property<string>("CoursesId")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("StudentsId")
                        .HasColumnType("varchar(256)");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("StudentTeachingCourse");
                });

            modelBuilder.Entity("InteractiveHub.Service.Discussion", b =>
                {
                    b.HasBaseType("InteractiveHub.Service.Activity");

                    b.Property<bool>("Discussion_AllowAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Discussion_MaxLength")
                        .HasColumnType("int");

                    b.Property<bool>("Discussion_RequireApproval")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("InteractiveHub.Service.Poll", b =>
                {
                    b.HasBaseType("InteractiveHub.Service.Activity");

                    b.Property<bool>("Poll_AllowMultipleSelections")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Poll_IsAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Poll_OptionsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("InteractiveHub.Service.Quiz", b =>
                {
                    b.HasBaseType("InteractiveHub.Service.Activity");

                    b.Property<string>("Quiz_QuestionsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Quiz_ShowCorrectAnswers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Quiz_ShuffleQuestions")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quiz_TimeLimit")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("InteractiveHub.Service.DiscussionSubmission", b =>
                {
                    b.HasBaseType("InteractiveHub.Service.Submission");

                    b.Property<bool>("Discussion_IsAnonymous")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isAnonymous");

                    b.Property<bool>("Discussion_IsApproved")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isApproved");

                    b.Property<string>("Discussion_Text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "text");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("InteractiveHub.Service.PollSubmission", b =>
                {
                    b.HasBaseType("InteractiveHub.Service.Submission");

                    b.Property<string>("Poll_SelectedOptionsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("InteractiveHub.Service.QuizSubmission", b =>
                {
                    b.HasBaseType("InteractiveHub.Service.Submission");

                    b.Property<string>("Quiz_AnswersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Quiz_Score")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "score");

                    b.Property<int>("Quiz_TimeSpent")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "timeSpent");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.AIConversationMessage", b =>
                {
                    b.HasOne("InteractiveHub.Service.ClassManagement.AIConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.AIPdfFile", b =>
                {
                    b.HasOne("InteractiveHub.Service.ClassManagement.AIConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.RealtimeClass", b =>
                {
                    b.HasOne("InteractiveHub.Service.ClassManagement.TeachingCourse", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("InteractiveHub.Service.Submission", b =>
                {
                    b.HasOne("InteractiveHub.Service.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentTeachingCourse", b =>
                {
                    b.HasOne("InteractiveHub.Service.ClassManagement.TeachingCourse", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteractiveHub.Service.ClassManagement.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InteractiveHub.Service.ClassManagement.TeachingCourse", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
