import { Box, Button, Card, Chip, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, InputAdornment, TextField, Tooltip, Typography } from '@mui/material';
import { useState } from 'react';

import { Iconify } from 'src/components/iconify';

export default function CourseDetailsStudentsTableToolbar({
    filters,
    onResetFilters,
    resultsCount = 0,
    totalCount = 0,
    onImportCSV,
    onAddStudent
}) {
    const { state: currentFilters, setState: updateFilters } = filters;
    const [showFormatDialog, setShowFormatDialog] = useState(false);

    const handleFiltersName = (event) => {
        updateFilters({ ...currentFilters, name: event.target.value });
    };

    const handleClearSearch = () => {
        updateFilters({ ...currentFilters, name: '' });
    };

    const handleImportClick = () => {
        // Trigger file input click
        const fileInput = document.getElementById('csv-file-input');
        fileInput?.click();
    };

    const processCSVFile = (file) => {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();

            reader.onload = (e) => {
                try {
                    const csvText = e.target.result;
                    const result = parseCSVToStudents(csvText);
                    resolve(result);
                } catch (error) {
                    reject(error);
                }
            };

            reader.onerror = () => {
                reject(new Error('Failed to read file'));
            };

            reader.readAsText(file);
        });
    };

    const parseCSVToStudents = (csvText) => {
        const lines = csvText.trim().split('\n');

        if (lines.length < 2) {
            throw new Error('CSV file must contain at least a header row and one data row');
        }

        // Get header row and normalize it
        const headers = lines[0].split(',').map(header => header.trim().toLowerCase().replace(/['"]/g, ''));

        // Create flexible mapping for different possible column names
        const columnMappings = {
            studentId: ['student id', 'studentid', 'student_id', 'id', 'student number', 'student no'],
            fullName: ['name', 'student name', 'full name', 'fullname'],
            email: ['email', 'email address', 'e-mail', 'mail'],
            pin: ['pin', 'password', 'access code', 'code']
        };

        // Find the actual column indices
        const columnIndices = {};

        Object.keys(columnMappings).forEach(key => {
            const possibleNames = columnMappings[key];
            const foundIndex = headers.findIndex(header =>
                possibleNames.some(name => header.includes(name))
            );
            if (foundIndex !== -1) {
                columnIndices[key] = foundIndex;
            }
        });

        // Check if we have the required columns
        if (columnIndices.studentId === undefined) {
            throw new Error('CSV must contain a "Student ID" column');
        }

        const students = [];
        const errors = [];

        // Process each data row
        for (let i = 1; i < lines.length; i++) {
            const line = lines[i].trim();
            if (!line) continue; // Skip empty lines

            const values = line.split(',').map(value => value.trim().replace(/^["']|["']$/g, ''));

            if (values.length < headers.length) {
                errors.push(`Row ${i + 1}: Expected ${headers.length} columns but got ${values.length}`);
                continue;
            }

            const student = {
                id: null, // Will be generated by backend
                isSelected: false, // For table selection
                studentId: columnIndices.studentId !== undefined ? values[columnIndices.studentId] : '',
                fullName: columnIndices.fullName !== undefined ? values[columnIndices.fullName] : '',
                email: columnIndices.email !== undefined ? values[columnIndices.email] : '',
                pin: columnIndices.pin !== undefined ? values[columnIndices.pin] : ''
            };

            // Validate that Student ID exists (required)
            if (!student.studentId || student.studentId.trim() === '') {
                errors.push(`Row ${i + 1}: Student ID is required and cannot be empty - row ignored`);
                continue;
            }

            // Generate fullName if missing but studentId exists
            if (!student.fullName || student.fullName.trim() === '') {
                student.fullName = `Student ${student.studentId}`;
            }

            // Add additional fields with defaults
            student.avatar = null;
            student.status = 'active';

            students.push(student);
        }

        // If there are errors but also some valid students, include error info in result
        const result = {
            students,
            errors,
            hasErrors: errors.length > 0
        };

        if (errors.length > 0) {
            const errorMessage = `Found ${errors.length} error(s):\n${errors.slice(0, 5).join('\n')}${errors.length > 5 ? '\n...and more' : ''}`;

            if (students.length === 0) {
                throw new Error(errorMessage);
            } else {
                console.warn(errorMessage);
                result.warningMessage = errorMessage;
            }
        }

        return result;
    };

    const handleFileChange = async (event) => {
        const file = event.target.files[0];

        if (!file) return;

        // Validate file type
        if (!file.name.toLowerCase().endsWith('.csv')) {
            alert('Please select a valid CSV file.');
            event.target.value = '';
            return;
        }

        try {
            const result = await processCSVFile(file);

            if (result.students.length === 0) {
                // No valid students found
                onImportCSV?.({
                    success: false,
                    errorMessage: 'No valid student data found in the CSV file.'
                });
                return;
            }

            // Call the parent callback with success result
            onImportCSV?.({
                success: true,
                students: result.students,
                ignoredCount: result.errors.length,
                errors: result.errors
            });

        } catch (error) {
            console.warn('CSV processing error:', error);

            // Call the parent callback with error result
            onImportCSV?.({
                success: false,
                errorMessage: error.message
            });
        }

        // Reset input value to allow re-selecting the same file
        event.target.value = '';
    };

    const handleShowFormat = () => {
        setShowFormatDialog(true);
    };

    const handleCloseFormat = () => {
        setShowFormatDialog(false);
    };

    const handleDownloadTemplate = () => {
        // Create CSV template content
        const templateContent = `Student ID,Name,Email,PIN
STU001,John Doe,john.doe@example.com,1234
STU002,Jane Smith,jane.smith@example.com,5678
STU003,Alice Johnson,alice.johnson@example.com,9012`;

        // Create blob and download
        const blob = new Blob([templateContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        const url = URL.createObjectURL(blob);

        link.setAttribute('href', url);
        link.setAttribute('download', 'student_import_template.csv');
        link.style.visibility = 'hidden';

        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);

        URL.revokeObjectURL(url);
    };

    const isFiltered = !!currentFilters.name;

    return (
        <Box
            sx={{
                p: 2.5,
                gap: 2,
                display: 'flex',
                pr: { xs: 2.5, md: 1 },
                flexDirection: { xs: 'column', md: 'row' },
                alignItems: { xs: 'flex-end', md: 'center' },
            }}
        >
            <Box
                sx={{
                    gap: 2,
                    width: 1,
                    flexGrow: 1,
                    display: 'flex',
                    alignItems: 'center',
                }}
            >
                <TextField
                    fullWidth
                    value={currentFilters.name}
                    onChange={handleFiltersName}
                    placeholder="Search students by ID, name, or email"
                    slotProps={{
                        input: {
                            startAdornment: (
                                <InputAdornment position="start">
                                    <Iconify icon="eva:search-fill" sx={{ color: 'text.disabled' }} />
                                </InputAdornment>
                            ),
                            endAdornment: currentFilters.name && (
                                <InputAdornment position="end">
                                    <IconButton
                                        onClick={handleClearSearch}
                                        edge="end"
                                        sx={{ color: 'text.disabled' }}
                                    >
                                        <Iconify icon="eva:close-fill" />
                                    </IconButton>
                                </InputAdornment>
                            ),
                        },
                    }}
                />

                {isFiltered && (
                    <Chip
                        size="small"
                        label={`${resultsCount} of ${totalCount} students`}
                        color={resultsCount > 0 ? 'primary' : 'default'}
                        variant="soft"
                    />
                )}
            </Box>

            {/* Hidden file input */}
            <input
                id="csv-file-input"
                type="file"
                accept=".csv"
                style={{ display: 'none' }}
                onChange={handleFileChange}
            />

            {/* Action Buttons */}
            <Box
                sx={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 1,
                    flexShrink: 0,
                }}
            >
                {/* Add Student Button */}
                <Tooltip title="Add a new student">
                    <Button
                        variant="contained"
                        startIcon={<Iconify icon="solar:user-plus-bold" />}
                        onClick={onAddStudent}
                        sx={{
                            flexShrink: 0,
                            textTransform: 'none',
                            fontWeight: 600,
                        }}
                    >
                        Add Student
                    </Button>
                </Tooltip>

                <Tooltip title="Import students from CSV">
                    <Button
                        variant="outlined"
                        startIcon={<Iconify icon="eva:upload-outline" />}
                        onClick={handleImportClick}
                        sx={{
                            flexShrink: 0,
                            textTransform: 'none',
                            fontWeight: 600,
                        }}
                    >
                        Import CSV
                    </Button>
                </Tooltip>

                <Tooltip title="View CSV format requirements">
                    <IconButton
                        onClick={handleShowFormat}
                        size="small"
                        sx={{
                            color: 'text.disabled',
                            '&:hover': { color: 'primary.main' },
                            flexShrink: 0,
                        }}
                    >
                        <Iconify icon="eva:question-mark-circle-outline" />
                    </IconButton>
                </Tooltip>
            </Box>

            {/* CSV Format Dialog */}
            <Dialog
                open={showFormatDialog}
                onClose={handleCloseFormat}
                maxWidth="sm"
                fullWidth
                aria-labelledby="format-dialog-title"
                aria-describedby="format-dialog-description"
                keepMounted={false}
                disableEnforceFocus={false}
                disableAutoFocus={false}
                disableRestoreFocus={false}
            >
                <DialogTitle id="format-dialog-title" sx={{ pb: 2 }}>
                    CSV Import Format
                </DialogTitle>
                <DialogContent id="format-dialog-description">
                    <Typography variant="body2" sx={{ mb: 2 }}>
                        Your CSV file can have columns in any order. The system will automatically detect the column names.
                    </Typography>

                    <Typography variant="subtitle2" sx={{ mb: 1 }}>
                        Supported Column Names (any order):
                    </Typography>
                    <Card sx={{ mb: 2, p: 2 }}>
                        <Typography variant="body2" sx={{ fontFamily: 'monospace' }}>
                            <strong>Student ID:</strong> "Student ID", "StudentID", "ID", "Student Number" <em>(Required)</em><br />
                            <strong>Name:</strong> "Name", "Student Name", "Full Name"<br />
                            <strong>Email:</strong> "Email", "Email Address", "E-mail"<br />
                            <strong>PIN:</strong> "PIN", "Password", "Access Code", "Code"
                        </Typography>
                    </Card>
                    <Typography variant="subtitle2" sx={{ mb: 1 }}>
                        Example (columns can be in any order):
                    </Typography>
                    <Card sx={{ mb: 2, p: 2 }}>
                        <Typography variant="body2" sx={{ fontFamily: 'monospace', }}>
                            Name,Email,Student ID,PIN<br />
                            John Doe,john.doe@example.com,STU001,1234<br />
                            Jane Smith,jane.smith@example.com,STU002,5678<br />
                            Alice Johnson,alice.johnson@example.com,STU003,9012
                        </Typography>
                    </Card>
                    <Typography variant="body2" color="text.secondary">
                        <strong>Notes:</strong><br />
                        • "Student ID" column is <strong>required</strong><br />
                        • Rows without Student ID will be ignored<br />
                        • Columns can be in any order<br />
                        • Column names are case-insensitive<br />
                        • Missing Names will be auto-generated from Student ID<br />
                        • Email and PIN are optional
                    </Typography>

                    <Typography variant="subtitle2" sx={{ mt: 3, mb: 1 }}>
                        Need a starting point?
                    </Typography>
                    <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                        Download the template file below, fill in your student data, and import it.
                    </Typography>
                </DialogContent>
                <DialogActions sx={{ justifyContent: 'space-between', px: 3, pb: 3 }}>
                    <Button
                        onClick={handleDownloadTemplate}
                        variant="outlined"
                        startIcon={<Iconify icon="eva:download-outline" />}
                        sx={{ textTransform: 'none' }}
                    >
                        Download Template
                    </Button>
                    <Button onClick={handleCloseFormat} color="primary" variant="contained">
                        Got it
                    </Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}
